### ISSUE TITLE
package writexl

### ISSUE THREAD

**Issue by jeroen** [r-wasm/webr-repo#20]
I am interested in using webr to convert data frames to xlsx. Would it be possible to try to build [writexl](https://cran.r-project.org/web/packages/writexl/index.html)? This package includes quite some C code but no dependencies otherwise.

**Comment by timelyportfolio** [comment]
@jeroen this is really ugly, but I think I finally have a test instance that builds/compiles `webR` and packages.  `writexl` seems to have built with no issues.  You can try it with 

```
const webR2 = new WebR({
  repoUrl: 'https://moonlit-chimera-8d3e09.netlify.app/repo/'
});
```

Please let me know if it does not work.  I'd love another tester to verify that my package build is working.

**Comment by georgestagg** [comment]
@timelyportfolio Your package repository looks correct at first glance, but I cannot easily test it from my machine because the [origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) is different from that of my my testing server, and my browser refuses the connection with a CORS error. 

You may need to tweak your netlify instance configuration to allow CORS, by ensuring the `Access-Control-Allow-Origin` HTTP header is set to `*`, and potentially setting other headers. There's a potentially useful Stack Overflow thread about that here: https://stackoverflow.com/questions/62507022/how-to-enable-cors-on-a-netlify-deployment

**Comment by timelyportfolio** [comment]
@georgestagg thank you so much!  Let me know how I can help going forward.  Currently, I am just randomly going through packages I think about and seeing if they work.  I'll try to start being more detailed in https://github.com/timelyportfolio/webr-repo/wiki/Other-Packages.

Also, one other note in case someone else tries to build, I had to change https://github.com/timelyportfolio/webr-repo/blob/main/repo-update.R#L117 to use `tarball` instead of `zipball` on my machine for remote repositories.
