### ISSUE TITLE
WebR hanging on 'Installing package dependencies'

### ISSUE THREAD

**Issue by DanielEWeeks** [r-wasm/webr-repo#29]
This morning I went to demo my example WebR page at

https://danieleweeks.github.io/HuGen2071/webR_test.html

and my demo failed in that it is failing to fully load WebR, hanging with the message `Installing package dependencies`, both in a Chrome browser and in a Safari browser.  Was wondering if `webr-repo` is down?  

WebR loads quickly if there are no R packages being installed - for example, it loads very quickly on this web page:

https://danieleweeks.github.io/HuGen2071/Rbasics.html

To get the Quarto WebR chunks to work in the Safari browser, I did recently revert back to [v0.1.0 (last version of CodeMirror)](https://github.com/coatless/quarto-webr/tree/0.1.0) by running in the Terminal tab of RStudio:

```
quarto add coatless/quarto-webr@0.1.0
```

See https://github.com/coatless/quarto-webr/issues/21

Quarto code for the example WebR page (with two back-ticks instead of three on the webr-r chunk to get it to display here OK):

```
---
title: WebR - R in the web browser
webr:
  packages: ['ggplot2']
---

This is a WebR-enabled code cell in a Quarto HTML document. As the WebR documentation states: "WebR makes it possible to run R code in the browser without the need for an R server to execute the code: the R interpreter runs directly on the user’s machine."

``{webr-r}
# Edit/add code here
fit = lm(mpg ~ am, data = mtcars)
summary(fit)
``

Link: [WebR](https://docs.r-wasm.org/webr/latest/).
---
```

**Comment by georgestagg** [comment]
I can see what's happening, the Matrix package is failing to load. It's happening because the latest version of webR is running R 4.3.0, and I have updated the `web-repo` repository since releasing version 0.1.1 of webR (used by that version of quarto-webr) which runs on R 4.1.0 instead.

It looks like `webr::install()` has a bug where when it reads the list of available packages, it does not take into account that binary versions of the packages may not be built for older versions of R. I will open an issue on the main repo for this.

This can be fixed, but the fix won't apply retrospectively to v0.1.1 of webR. So, in the meantime I will try and manually build the Matrix package for v0.1.1 and upload it to the public repo.

Which R packages are you planning to use? There may be other packages with the same issue.

**Comment by DanielEWeeks** [comment]
Thank you for the explanation.

Maybe it would be simplest in my Quarto book to just use the latest version of WebR and tell our users to use Chrome or Firefox browsers and not to use Safari.

Anyway, so far, I'm using these packages:

```
 packages: ['stringr','tidyr']
 packages: ['ggplot2']
```

**Comment by georgestagg** [comment]
Those packages should hopefully be working now, even in the older version of webR. Though, you might need to clear your browser cache. I'll keep an eye on this for the moment, but it's likely as time goes on the same issue will occur and older webR versions won't be able to use the latest version of packages uploaded to the public webr-repo.

> Maybe it would be simplest in my Quarto book to just use the latest version of WebR

Probably the right thing to do is to keep the version of the quarto-webr extension you are using updated, and ideally the extension will be updated by that team as new versions of webR are released. Once this original bug is fixed in webR, and quarto-webr has updated to use that version, the `webr::install()` issue should no longer be a problem in your book.

IIUC the Safari issue is a problem with the Monaco editor used by the quarto-webr extension, rather than an issue with webR. I don't think there is much that can be done from the webR side to help with that.

I'm going to close this in favour of r-wasm/webr#245, but feel free to continue the conversation here if you continue to have issues loading packages in the short term.
